media_build: add SET_SYSTEM_SLEEP_PM_OPS definition to compat.h Old kernels are missing the definition of SET_SYSTEM_SLEEP_PM_OPS in linux/pm.h:
media_build/v4l/msp3400-driver.c:871:2: error: implicit declaration of function 'SET_SYSTEM_SLEEP_PM_OPS' [-Werror=implicit-function-declaration]
media_build/v4l/msp3400-driver.c:872:1: error: initializer element is not constant
media_build/v4l/msp3400-driver.c:872:1: error: (near initialization for 'msp3400_pm_ops.prepare')

Add it to compat.h to fix the compilation breakage.

Signed-off-by: Gianluca Gennari <gennarone@gmail.com
Signed-off-by: Hans Verkuil <hans.verkuil@cisco.com>
---
 v4l/compat.h                      |   14 ++++++++++++++
 v4l/scripts/make_config_compat.pl |    1 +
 2 files changed, 15 insertions(+)